//
// Generated by JTB 1.3.2
//

package jsrc.matlab.syntaxanalysis.visitor;
import jsrc.matlab.syntaxanalysis.syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( FunctionHeader() )?
    * f1 -> ( Statement() )*
    * f2 -> <EOF>
    */
   public R visit(File n, A argu);

   /**
    * f0 -> "function"
    * f1 -> [ OutputClause() ]
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( IdentifierList() )?
    * f5 -> ")"
    * f6 -> ( ";" )?
    */
   public R visit(FunctionHeader n, A argu);

   /**
    * f0 -> Output()
    * f1 -> "="
    */
   public R visit(OutputClause n, A argu);

   /**
    * f0 -> Identifier()
    *       | MultiOutput()
    */
   public R visit(Output n, A argu);

   /**
    * f0 -> "["
    * f1 -> IdentifierList()
    * f2 -> "]"
    */
   public R visit(MultiOutput n, A argu);

   /**
    * f0 -> CommandList()
    *       | ArrayUpdate()
    *       | CallSt()
    *       | AssignmentSt()
    *       | CallAndMultipleAssignmentSt()
    *       | IfSt()
    *       | ForSt()
    *       | WhileSt()
    *       | SwitchSt()
    *       | BreakSt()
    *       | ReturnSt()
    *       | Tic()
    *       | PrintSt()
    *       | PrintlnSt()
    */
   public R visit(Statement n, A argu);

   /**
    * f0 -> "tic"
    * f1 -> [ ";" ]
    */
   public R visit(Tic n, A argu);

   /**
Identifier()
    * f0 -> [ Identifier() ]
    */
   public R visit(Command n, A argu);

   /**
    * f0 -> Call()
    * f1 -> [ ";" ]
    */
   public R visit(CallSt n, A argu);

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> [ ";" ]
    */
   public R visit(AssignmentSt n, A argu);

   /**
    * f0 -> "["
    * f1 -> IdentifierList()
    * f2 -> "]"
    * f3 -> "="
    * f4 -> Call()
    * f5 -> [ ";" ]
    */
   public R visit(CallAndMultipleAssignmentSt n, A argu);

   /**
    * f0 -> IndexedArray()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> [ ";" ]
    */
   public R visit(ArrayUpdate n, A argu);

   /**
    * f0 -> "if"
    * f1 -> Expression()
    * f2 -> ( Statement() )*
    * f3 -> ( ElseIf() )*
    * f4 -> ( ElseClause() )?
    * f5 -> "end"
    */
   public R visit(IfSt n, A argu);

   /**
    * f0 -> "elseif"
    * f1 -> Expression()
    * f2 -> ( Statement() )*
    */
   public R visit(ElseIf n, A argu);

   /**
    * f0 -> "else"
    * f1 -> ( Statement() )*
    */
   public R visit(ElseClause n, A argu);

   /**
    * f0 -> "for"
    * f1 -> Identifier()
    * f2 -> "="
    * f3 -> Expression()
    * f4 -> ( Statement() )*
    * f5 -> "end"
    */
   public R visit(ForSt n, A argu);

   /**
    * f0 -> "while"
    * f1 -> Expression()
    * f2 -> ( Statement() )*
    * f3 -> "end"
    */
   public R visit(WhileSt n, A argu);

   /**
    * f0 -> "switch"
    * f1 -> Expression()
    * f2 -> ( Case() )*
    * f3 -> "otherwise"
    * f4 -> ( Statement() )*
    * f5 -> "end"
    */
   public R visit(SwitchSt n, A argu);

   /**
    * f0 -> "case"
    * f1 -> ( StringLiteral() | IntegerLiteral() )
    * f2 -> ( Statement() )*
    */
   public R visit(Case n, A argu);

   /**
    * f0 -> "break"
    * f1 -> ";"
    */
   public R visit(BreakSt n, A argu);

   /**
    * f0 -> "return"
    * f1 -> ";"
    */
   public R visit(ReturnSt n, A argu);

   /**
    * f0 -> "print("
    * f1 -> Expression()
    * f2 -> ")"
    * f3 -> ( ";" )?
    */
   public R visit(PrintSt n, A argu);

   /**
    * f0 -> "println("
    * f1 -> Expression()
    * f2 -> ")"
    * f3 -> ( ";" )?
    */
   public R visit(PrintlnSt n, A argu);

   /**
    * f0 -> ShortCircuitOrExp()
    */
   public R visit(Expression n, A argu);

   /**
    * f0 -> ShortCircuitAndExp()
    * f1 -> ( ShortCircuitOrExpRest() )*
    */
   public R visit(ShortCircuitOrExp n, A argu);

   /**
    * f0 -> "||"
    * f1 -> ShortCircuitAndExp()
    */
   public R visit(ShortCircuitOrExpRest n, A argu);

   /**
    * f0 -> ElementWiseOrExp()
    * f1 -> ( ShortCircuitAndExpRest() )*
    */
   public R visit(ShortCircuitAndExp n, A argu);

   /**
    * f0 -> "&&"
    * f1 -> ElementWiseOrExp()
    */
   public R visit(ShortCircuitAndExpRest n, A argu);

   /**
    * f0 -> ElementWiseAndExp()
    * f1 -> ( ElementWiseOrExpRest() )*
    */
   public R visit(ElementWiseOrExp n, A argu);

   /**
    * f0 -> "|"
    * f1 -> ElementWiseAndExp()
    */
   public R visit(ElementWiseOrExpRest n, A argu);

   /**
    * f0 -> RelationalExp()
    * f1 -> ( ElementWiseAndExpRest() )*
    */
   public R visit(ElementWiseAndExp n, A argu);

   /**
    * f0 -> "&"
    * f1 -> RelationalExp()
    */
   public R visit(ElementWiseAndExpRest n, A argu);

   /**
    * f0 -> ColonVectorExp()
    * f1 -> ( RelationalExpRest() )?
    */
   public R visit(RelationalExp n, A argu);

   /**
    * f0 -> ( "<" | ">" | "<=" | ">=" | "==" | "~=" )
    * f1 -> ColonVectorExp()
    */
   public R visit(RelationalExpRest n, A argu);

   /**
    * f0 -> Term()
    * f1 -> [ ":" Term() [ ":" Term() ] ]
    */
   public R visit(ColonVectorExp n, A argu);

   /**
    * f0 -> Factor()
    * f1 -> ( TermRest() )*
    */
   public R visit(Term n, A argu);

   /**
    * f0 -> ( "+" | "-" )
    * f1 -> Factor()
    */
   public R visit(TermRest n, A argu);

   /**
    * f0 -> UnaryExp()
    * f1 -> ( FactorRest() )*
    */
   public R visit(Factor n, A argu);

   /**
    * f0 -> ( "*" | ".*" | "/" | "./" )
    * f1 -> UnaryExp()
    */
   public R visit(FactorRest n, A argu);

   /**
    * f0 -> [ "-" | "~" ]
    * f1 -> SuperScriptExp()
    */
   public R visit(UnaryExp n, A argu);

   /**
    * f0 -> TransposeExp()
    *       | PowerExp()
    */
   public R visit(SuperScriptExp n, A argu);

   /**
    * f0 -> AtomExp()
    * f1 -> "'"
    */
   public R visit(TransposeExp n, A argu);

   /**
    * f0 -> AtomExp()
    * f1 -> ( PowerExpRest() )*
    */
   public R visit(PowerExp n, A argu);

   /**
    * f0 -> ( ".^" | "^" )
    * f1 -> AtomExp()
    */
   public R visit(PowerExpRest n, A argu);

   /**
    * f0 -> CallOrIndexedArray()
    *       | ParExp()
    *       | MatrixConstructor()
    *       | IntegerLiteral()
    *       | FloatingPointLiteral()
    *       | StringLiteral()
    *       | Identifier()
    *       | "toc"
    *       | ":"
    *       | "end"
    */
   public R visit(AtomExp n, A argu);

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(ParExp n, A argu);

   /**
    * f0 -> CallOrIndexedArray()
    */
   public R visit(Call n, A argu);

   /**
    * f0 -> CallOrIndexedArray()
    */
   public R visit(IndexedArray n, A argu);

   /**
    * f0 -> Identifier()
    * f1 -> "("
    * f2 -> ( ExpressionList() )?
    * f3 -> ")"
    */
   public R visit(CallOrIndexedArray n, A argu);

   /**
    * f0 -> "["
    * f1 -> ( ExpressionSeqs() "]" | "]" )
    */
   public R visit(MatrixConstructor n, A argu);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu);

   /**
    * f0 -> <FLOATING_POINT_LITERAL>
    */
   public R visit(FloatingPointLiteral n, A argu);

   /**
    * f0 -> <STRING_LITERAL>
    */
   public R visit(StringLiteral n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu);

   /**
    * f0 -> Identifier()
    * f1 -> ( IdentifierRest() )*
    */
   public R visit(IdentifierList n, A argu);

   /**
    * f0 -> ","
    * f1 -> Identifier()
    */
   public R visit(IdentifierRest n, A argu);

   /**
    * f0 -> Command()
    * f1 -> ( CommandsRest() )*
    * f2 -> [ ";" ]
    */
   public R visit(CommandList n, A argu);

   /**
    * f0 -> ","
    * f1 -> Command()
    */
   public R visit(CommandsRest n, A argu);

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu);

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu);

   /**
    * f0 -> Expression()
    * f1 -> ( ( "," )? Expression() )*
    */
   public R visit(ExpressionSeq n, A argu);

   /**
    * f0 -> ExpressionSeq()
    * f1 -> ( ExpressionSeqsRest() )*
    */
   public R visit(ExpressionSeqs n, A argu);

   /**
    * f0 -> ";"
    * f1 -> ExpressionSeq()
    */
   public R visit(ExpressionSeqsRest n, A argu);

}
