//
// Generated by JTB 1.3.2
//

package jsrc.matlab.syntaxanalysis.visitor;
import jsrc.matlab.syntaxanalysis.syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( FunctionHeader() )?
    * f1 -> ( Statement() )*
    * f2 -> <EOF>
    */
   public void visit(File n);

   /**
    * f0 -> "function"
    * f1 -> [ OutputClause() ]
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( IdentifierList() )?
    * f5 -> ")"
    * f6 -> ( ";" )?
    */
   public void visit(FunctionHeader n);

   /**
    * f0 -> Output()
    * f1 -> "="
    */
   public void visit(OutputClause n);

   /**
    * f0 -> Identifier()
    *       | MultiOutput()
    */
   public void visit(Output n);

   /**
    * f0 -> "["
    * f1 -> IdentifierList()
    * f2 -> "]"
    */
   public void visit(MultiOutput n);

   /**
    * f0 -> CommandList()
    *       | ArrayUpdate()
    *       | CallSt()
    *       | AssignmentSt()
    *       | CallAndMultipleAssignmentSt()
    *       | IfSt()
    *       | ForSt()
    *       | WhileSt()
    *       | SwitchSt()
    *       | BreakSt()
    *       | ReturnSt()
    *       | Tic()
    *       | PrintSt()
    *       | PrintlnSt()
    */
   public void visit(Statement n);

   /**
    * f0 -> "tic"
    * f1 -> [ ";" ]
    */
   public void visit(Tic n);

   /**
Identifier()
    * f0 -> [ Identifier() ]
    */
   public void visit(Command n);

   /**
    * f0 -> Call()
    * f1 -> [ ";" ]
    */
   public void visit(CallSt n);

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> [ ";" ]
    */
   public void visit(AssignmentSt n);

   /**
    * f0 -> "["
    * f1 -> IdentifierList()
    * f2 -> "]"
    * f3 -> "="
    * f4 -> Call()
    * f5 -> [ ";" ]
    */
   public void visit(CallAndMultipleAssignmentSt n);

   /**
    * f0 -> IndexedArray()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> [ ";" ]
    */
   public void visit(ArrayUpdate n);

   /**
    * f0 -> "if"
    * f1 -> Expression()
    * f2 -> ( Statement() )*
    * f3 -> ( ElseIf() )*
    * f4 -> ( ElseClause() )?
    * f5 -> "end"
    */
   public void visit(IfSt n);

   /**
    * f0 -> "elseif"
    * f1 -> Expression()
    * f2 -> ( Statement() )*
    */
   public void visit(ElseIf n);

   /**
    * f0 -> "else"
    * f1 -> ( Statement() )*
    */
   public void visit(ElseClause n);

   /**
    * f0 -> "for"
    * f1 -> Identifier()
    * f2 -> "="
    * f3 -> Expression()
    * f4 -> ( Statement() )*
    * f5 -> "end"
    */
   public void visit(ForSt n);

   /**
    * f0 -> "while"
    * f1 -> Expression()
    * f2 -> ( Statement() )*
    * f3 -> "end"
    */
   public void visit(WhileSt n);

   /**
    * f0 -> "switch"
    * f1 -> Expression()
    * f2 -> ( Case() )*
    * f3 -> "otherwise"
    * f4 -> ( Statement() )*
    * f5 -> "end"
    */
   public void visit(SwitchSt n);

   /**
    * f0 -> "case"
    * f1 -> ( StringLiteral() | IntegerLiteral() )
    * f2 -> ( Statement() )*
    */
   public void visit(Case n);

   /**
    * f0 -> "break"
    * f1 -> ";"
    */
   public void visit(BreakSt n);

   /**
    * f0 -> "return"
    * f1 -> ";"
    */
   public void visit(ReturnSt n);

   /**
    * f0 -> "print("
    * f1 -> Expression()
    * f2 -> ")"
    * f3 -> ( ";" )?
    */
   public void visit(PrintSt n);

   /**
    * f0 -> "println("
    * f1 -> Expression()
    * f2 -> ")"
    * f3 -> ( ";" )?
    */
   public void visit(PrintlnSt n);

   /**
    * f0 -> ShortCircuitOrExp()
    */
   public void visit(Expression n);

   /**
    * f0 -> ShortCircuitAndExp()
    * f1 -> ( ShortCircuitOrExpRest() )*
    */
   public void visit(ShortCircuitOrExp n);

   /**
    * f0 -> "||"
    * f1 -> ShortCircuitAndExp()
    */
   public void visit(ShortCircuitOrExpRest n);

   /**
    * f0 -> ElementWiseOrExp()
    * f1 -> ( ShortCircuitAndExpRest() )*
    */
   public void visit(ShortCircuitAndExp n);

   /**
    * f0 -> "&&"
    * f1 -> ElementWiseOrExp()
    */
   public void visit(ShortCircuitAndExpRest n);

   /**
    * f0 -> ElementWiseAndExp()
    * f1 -> ( ElementWiseOrExpRest() )*
    */
   public void visit(ElementWiseOrExp n);

   /**
    * f0 -> "|"
    * f1 -> ElementWiseAndExp()
    */
   public void visit(ElementWiseOrExpRest n);

   /**
    * f0 -> RelationalExp()
    * f1 -> ( ElementWiseAndExpRest() )*
    */
   public void visit(ElementWiseAndExp n);

   /**
    * f0 -> "&"
    * f1 -> RelationalExp()
    */
   public void visit(ElementWiseAndExpRest n);

   /**
    * f0 -> ColonVectorExp()
    * f1 -> ( RelationalExpRest() )?
    */
   public void visit(RelationalExp n);

   /**
    * f0 -> ( "<" | ">" | "<=" | ">=" | "==" | "~=" )
    * f1 -> ColonVectorExp()
    */
   public void visit(RelationalExpRest n);

   /**
    * f0 -> Term()
    * f1 -> [ ":" Term() [ ":" Term() ] ]
    */
   public void visit(ColonVectorExp n);

   /**
    * f0 -> Factor()
    * f1 -> ( TermRest() )*
    */
   public void visit(Term n);

   /**
    * f0 -> ( "+" | "-" )
    * f1 -> Factor()
    */
   public void visit(TermRest n);

   /**
    * f0 -> UnaryExp()
    * f1 -> ( FactorRest() )*
    */
   public void visit(Factor n);

   /**
    * f0 -> ( "*" | ".*" | "/" | "./" )
    * f1 -> UnaryExp()
    */
   public void visit(FactorRest n);

   /**
    * f0 -> [ "-" | "~" ]
    * f1 -> SuperScriptExp()
    */
   public void visit(UnaryExp n);

   /**
    * f0 -> TransposeExp()
    *       | PowerExp()
    */
   public void visit(SuperScriptExp n);

   /**
    * f0 -> AtomExp()
    * f1 -> "'"
    */
   public void visit(TransposeExp n);

   /**
    * f0 -> AtomExp()
    * f1 -> ( PowerExpRest() )*
    */
   public void visit(PowerExp n);

   /**
    * f0 -> ( ".^" | "^" )
    * f1 -> AtomExp()
    */
   public void visit(PowerExpRest n);

   /**
    * f0 -> CallOrIndexedArray()
    *       | ParExp()
    *       | MatrixConstructor()
    *       | IntegerLiteral()
    *       | FloatingPointLiteral()
    *       | StringLiteral()
    *       | Identifier()
    *       | "toc"
    *       | ":"
    *       | "end"
    */
   public void visit(AtomExp n);

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public void visit(ParExp n);

   /**
    * f0 -> CallOrIndexedArray()
    */
   public void visit(Call n);

   /**
    * f0 -> CallOrIndexedArray()
    */
   public void visit(IndexedArray n);

   /**
    * f0 -> Identifier()
    * f1 -> "("
    * f2 -> ( ExpressionList() )?
    * f3 -> ")"
    */
   public void visit(CallOrIndexedArray n);

   /**
    * f0 -> "["
    * f1 -> ( ExpressionSeqs() "]" | "]" )
    */
   public void visit(MatrixConstructor n);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n);

   /**
    * f0 -> <FLOATING_POINT_LITERAL>
    */
   public void visit(FloatingPointLiteral n);

   /**
    * f0 -> <STRING_LITERAL>
    */
   public void visit(StringLiteral n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Identifier n);

   /**
    * f0 -> Identifier()
    * f1 -> ( IdentifierRest() )*
    */
   public void visit(IdentifierList n);

   /**
    * f0 -> ","
    * f1 -> Identifier()
    */
   public void visit(IdentifierRest n);

   /**
    * f0 -> Command()
    * f1 -> ( CommandsRest() )*
    * f2 -> [ ";" ]
    */
   public void visit(CommandList n);

   /**
    * f0 -> ","
    * f1 -> Command()
    */
   public void visit(CommandsRest n);

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public void visit(ExpressionList n);

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public void visit(ExpressionRest n);

   /**
    * f0 -> Expression()
    * f1 -> ( ( "," )? Expression() )*
    */
   public void visit(ExpressionSeq n);

   /**
    * f0 -> ExpressionSeq()
    * f1 -> ( ExpressionSeqsRest() )*
    */
   public void visit(ExpressionSeqs n);

   /**
    * f0 -> ";"
    * f1 -> ExpressionSeq()
    */
   public void visit(ExpressionSeqsRest n);

}

