//
// Generated by JTB 1.3.2
//

package jsrc.px10.syntaxanalyser.syntaxtree;

/**
 * Grammar production:
 * f0 -> "region"
 * f1 -> "("
 * f2 -> ":"
 * f3 -> RankEquation()
 * f4 -> ")"
 */
public class RegionType implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;
   public RankEquation f3;
   public NodeToken f4;

   public RegionType(NodeToken n0, NodeToken n1, NodeToken n2, RankEquation n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public RegionType(RankEquation n0) {
      f0 = new NodeToken("region");
      f1 = new NodeToken("(");
      f2 = new NodeToken(":");
      f3 = n0;
      f4 = new NodeToken(")");
   }

   public void accept(jsrc.px10.syntaxanalyser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jsrc.px10.syntaxanalyser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jsrc.px10.syntaxanalyser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jsrc.px10.syntaxanalyser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

