//
// Generated by JTB 1.3.2
//

package jsrc.matlab.syntaxanalysis.syntaxtree;

/**
 * Grammar production:
 * f0 -> "switch"
 * f1 -> Expression()
 * f2 -> ( Case() )*
 * f3 -> "otherwise"
 * f4 -> ( Statement() )*
 * f5 -> "end"
 */
public class SwitchSt implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeListOptional f2;
   public NodeToken f3;
   public NodeListOptional f4;
   public NodeToken f5;

   public SwitchSt(NodeToken n0, Expression n1, NodeListOptional n2, NodeToken n3, NodeListOptional n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public SwitchSt(Expression n0, NodeListOptional n1, NodeListOptional n2) {
      f0 = new NodeToken("switch");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("otherwise");
      f4 = n2;
      f5 = new NodeToken("end");
   }

   public void accept(jsrc.matlab.syntaxanalysis.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jsrc.matlab.syntaxanalysis.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jsrc.matlab.syntaxanalysis.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jsrc.matlab.syntaxanalysis.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

