#!/bin/sh
export CURRENT="/media/MOHSENHD/1.Works/3.Research/0.Research/2.Plasma/2.Project/Project/src/x10/translatedbenchs/hand/mapreduce/generic"
export SET_DIR="/media/MOHSENHD/1.Works/3.Research/0.Research/2.Plasma/2.Project/Project/LaunchBenchmarks"
clear
clear
echo ===============================================================
echo MapReduce benchmark - V2.0 Generic
echo -----------------------------------
cd $SET_DIR
. ./SetEnvForV2
echo Compile
cd $CURRENT
#x10c++ Timer.x10
#x10c++ Mapper.x10
#x10c++ Reducer.x10
#x10c++ MapReducer.x10
x10c++ -MAIN_CLASS=MapReduceLauncher MapReduceLauncher.x10
cd $CURRENT
echo ===============================================================

