//
// Generated by JTB 1.3.2
//

package jsrc.px10.syntaxanalyser.syntaxtree;

/**
 * Grammar production:
 * f0 -> PrimaryExpression()
 * f1 -> "--"
 */
public class PostDecrementExpression implements Node {
   public PrimaryExpression f0;
   public NodeToken f1;

   public PostDecrementExpression(PrimaryExpression n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public PostDecrementExpression(PrimaryExpression n0) {
      f0 = n0;
      f1 = new NodeToken("--");
   }

   public void accept(jsrc.px10.syntaxanalyser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jsrc.px10.syntaxanalyser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jsrc.px10.syntaxanalyser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jsrc.px10.syntaxanalyser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

