//
// Generated by JTB 1.3.2
//

package jsrc.matlab.syntaxanalysis.syntaxtree;

/**
 * Grammar production:
 * f0 -> "if"
 * f1 -> Expression()
 * f2 -> ( Statement() )*
 * f3 -> ( ElseIf() )*
 * f4 -> ( ElseClause() )?
 * f5 -> "end"
 */
public class IfSt implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeListOptional f2;
   public NodeListOptional f3;
   public NodeOptional f4;
   public NodeToken f5;

   public IfSt(NodeToken n0, Expression n1, NodeListOptional n2, NodeListOptional n3, NodeOptional n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public IfSt(Expression n0, NodeListOptional n1, NodeListOptional n2, NodeOptional n3) {
      f0 = new NodeToken("if");
      f1 = n0;
      f2 = n1;
      f3 = n2;
      f4 = n3;
      f5 = new NodeToken("end");
   }

   public void accept(jsrc.matlab.syntaxanalysis.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jsrc.matlab.syntaxanalysis.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jsrc.matlab.syntaxanalysis.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jsrc.matlab.syntaxanalysis.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

