//
// Generated by JTB 1.3.2
//

package jsrc.matlab.syntaxanalysis.syntaxtree;

/**
 * Grammar production:
 * f0 -> "println("
 * f1 -> Expression()
 * f2 -> ")"
 * f3 -> ( ";" )?
 */
public class PrintlnSt implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeToken f2;
   public NodeOptional f3;

   public PrintlnSt(NodeToken n0, Expression n1, NodeToken n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public PrintlnSt(Expression n0, NodeOptional n1) {
      f0 = new NodeToken("println(");
      f1 = n0;
      f2 = new NodeToken(")");
      f3 = n1;
   }

   public void accept(jsrc.matlab.syntaxanalysis.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jsrc.matlab.syntaxanalysis.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jsrc.matlab.syntaxanalysis.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jsrc.matlab.syntaxanalysis.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

