//
// Generated by JTB 1.3.2
//

package jsrc.matlab.syntaxanalysis.syntaxtree;

/**
 * Grammar production:
 * f0 -> CommandList()
 *       | ArrayUpdate()
 *       | CallSt()
 *       | AssignmentSt()
 *       | CallAndMultipleAssignmentSt()
 *       | IfSt()
 *       | ForSt()
 *       | WhileSt()
 *       | SwitchSt()
 *       | BreakSt()
 *       | ReturnSt()
 *       | Tic()
 *       | PrintSt()
 *       | PrintlnSt()
 */
public class Statement implements Node {
   public NodeChoice f0;

   public Statement(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(jsrc.matlab.syntaxanalysis.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jsrc.matlab.syntaxanalysis.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jsrc.matlab.syntaxanalysis.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jsrc.matlab.syntaxanalysis.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

