//
// Generated by JTB 1.3.2
//

package jsrc.matlab.syntaxanalysis.syntaxtree;

/**
 * Grammar production:
 * f0 -> "while"
 * f1 -> Expression()
 * f2 -> ( Statement() )*
 * f3 -> "end"
 */
public class WhileSt implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeListOptional f2;
   public NodeToken f3;

   public WhileSt(NodeToken n0, Expression n1, NodeListOptional n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public WhileSt(Expression n0, NodeListOptional n1) {
      f0 = new NodeToken("while");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("end");
   }

   public void accept(jsrc.matlab.syntaxanalysis.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jsrc.matlab.syntaxanalysis.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jsrc.matlab.syntaxanalysis.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jsrc.matlab.syntaxanalysis.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

